### ISSUE TITLE
Some team members' photo doesn't appear on the project page

### ISSUE THREAD

**Issue by okkhoy** [AY1920S1-CS2113T-F10-2/main#181]
Check: https://nuscs2113-ay1920s1.github.io/website/admin/projectList.html#f10-2

Read:
![image](https://user-images.githubusercontent.com/1023494/68544448-3d1b5780-03fe-11ea-93c8-885cd8f38ff8.png)

**Comment by KaneQuah** [comment]
Issue images resolved
